### ISSUE TITLE
Errors with gRPC projections and autoscaling

### ISSUE THREAD

**Issue by pvlugter** [akka/akka-projection#1025]
Haven't looked into this yet, but noting here for follow up. When running the local-drone-control service with autoscaling, getting errors on the restaurant-drone-deliveries side. Most likely when the vertical scaling evicts and recreates pods. Restarting the restaurant-drone-deliveries service with clean database and it reruns the projections without problems. Types of errors:

```
[ERROR] [akka.persistence.typed.internal.EventWriter$] [akka://restaurant-drone-deliveries@127.0.0.1:2551] [] [restaurant-drone-deliveries-akka.actor.default-dispatcher-28] - Supervisor RestartSupervisor saw failure: Got unexpected reply from journal class akka.persistence.JournalProtocol$ReplayMessagesFailure for pid Drone|drone-077
java.lang.IllegalArgumentException: Got unexpected reply from journal class akka.persistence.JournalProtocol$ReplayMessagesFailure for pid Drone|drone-077
 at akka.persistence.typed.internal.EventWriter$.$anonfun$apply$6(EventWriter.scala:237)
 at akka.actor.typed.internal.AdaptMessage.adapt(InternalMessage.scala:29)
 at akka.actor.typed.internal.adapter.ActorAdapter.$anonfun$aroundReceive$1(ActorAdapter.scala:97)
 at akka.actor.typed.internal.adapter.ActorAdapter.withSafelyAdapted(ActorAdapter.scala:193)
 at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:97)
 at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
 at akka.actor.ActorCell.invoke(ActorCell.scala:547)
 at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
 at akka.dispatch.Mailbox.run(Mailbox.scala:231)
 at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
 at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
 at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
 at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
 at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
 at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

```
[WARN] [akka.projection.r2dbc.internal.R2dbcOffsetStore] [] [] [restaurant-drone-deliveries-akka.actor.default-dispatcher-18] - Rejecting unexpected sequence number [465] for pid [Drone|drone-400], previous sequence number [463]. Offset: TimestampOffset(2023-10-02T01:06:13.593647Z,2023-10-02T01:08:58.319774Z,Map(Drone|drone-400 -> 465))
[ERROR] [akka.projection.r2dbc.internal.R2dbcProjectionImpl] [akka://restaurant-drone-deliveries@127.0.0.1:2551] [] [restaurant-drone-deliveries-akka.actor.default-dispatcher-18] - [DroneEvents-drone-0-255] Failed to process envelope with offset [TimestampOffset(2023-10-02T01:06:13.593647Z,2023-10-02T01:08:58.319774Z,Map(Drone|drone-400 -> 465))]. Projection will stop as defined by recovery strategy.
akka.projection.r2dbc.internal.R2dbcOffsetStore$RejectedEnvelope: Rejected envelope from backtracking, persistenceId [Drone|drone-400], seqNr [465] due to unexpected sequence number.
 at akka.projection.r2dbc.internal.R2dbcProjectionImpl$.akka$projection$r2dbc$internal$R2dbcProjectionImpl$$throwRejectedEnvelope(R2dbcProjectionImpl.scala:472)
 at akka.projection.r2dbc.internal.R2dbcProjectionImpl$$anon$4.$anonfun$process$17(R2dbcProjectionImpl.scala:353)
 at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
 at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:64)
 at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:101)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
 at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
 at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:101)
 at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
 at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
 at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
 at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
 at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
 at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
 at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

```
[WARN] [akka.projection.grpc.internal.EventPusherConsumerServiceImpl] [] [] [restaurant-drone-deliveries-akka.actor.default-dispatcher-17] - Failing event stream because of event writer error
java.util.concurrent.TimeoutException: Ask timed out on [Actor[akka://restaurant-drone-deliveries/system/EventWriter-default#-1894454461]] after [5000 ms]. Message of type [akka.persistence.typed.internal.EventWriter$Write]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.
 at akka.actor.typed.scaladsl.AskPattern$.$anonfun$onTimeout$1(AskPattern.scala:132)
 at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:730)
 at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:478)
 at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
 at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:365)
 at akka.actor.LightArrayRevolverScheduler$$anon$3.executeBucket$1(LightArrayRevolverScheduler.scala:314)
 at akka.actor.LightArrayRevolverScheduler$$anon$3.nextTick(LightArrayRevolverScheduler.scala:318)
 at akka.actor.LightArrayRevolverScheduler$$anon$3.run(LightArrayRevolverScheduler.scala:270)
 at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by patriknw** [comment]
It's a missing case for `ReplayMessagesFailure` in `EventWriter.askMaxSeqNr`, but that is already in an error scenario via `WriteMessageFailure`, which could be because of a duplicate sequence number (expected case), but maybe it's something else with the db? Now we don't see any of the original errors.

**Comment by patriknw** [comment]
Started fix in https://github.com/akka/akka/pull/32148

**Comment by pvlugter** [comment]
I'll look at getting the underlying errors, and check what's needed to reproduce this.

**Comment by pvlugter** [comment]
Haven't had a chance to look at reproducing more closely. But the original error is `duplicate key value violates unique constraint "event_journal_pkey"` — so some overlap when scaling on the other side?

**Comment by patriknw** [comment]
Duplicate key violation is expected for at-least once. The EventWriter optimistically writes the incoming event and if it has the same pid/seqNr as already written it will be a violation. We can't know if that error from WriteMessageFailure response is a duplicate violation or some other error. Therefore we query the max seqNr to decide if it's a duplicate or not. The ReplayMessagesFailure is from that latter query. Still interesting to understand why that query failed.

**Comment by pvlugter** [comment]
Ok. See now that the cause is circuit breaker open exception. So if there are several duplicate key violations in short time from the optimistic writes, it trips the circuit breaker, and then no queries will be successful for a while, including query on max sequence number?

**Comment by patriknw** [comment]
Ah, that makes sense, and is something that we have to solve. There will be bursts of many duplicates.

**Comment by patriknw** [comment]
fix in https://github.com/akka/akka/pull/32153

**Comment by patriknw** [comment]
Closing since it is supposed to be fixed by the two PRs in Akka
