### ISSUE TITLE
faile: wrong logger loaded

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#106]
Test failure with:

```scala
[info] HandlerRecoveryImplSpec:
[info] akka.projection.internal.HandlerRecoveryImplSpec *** ABORTED *** (2 milliseconds)
SLF4J: A number (3) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
[info]   java.lang.IllegalArgumentException: Requires Logback logger for [], it was a [org.slf4j.helpers.SubstituteLogger]
[info]   at akka.actor.testkit.typed.internal.LogbackUtil$.getLogbackLogger(LogbackUtil.scala:26)
[info]   at akka.actor.testkit.typed.internal.CapturingAppender$.get(CapturingAppender.scala:21)
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.$init$(LogCapturing.scala:36)
[info]   at akka.projection.internal.HandlerRecoveryImplSpec.<init>(HandlerRecoveryImplSpec.scala:43)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

**Comment by renatocaval** [comment]
Happened in #103. Only difference in that module is that I added akka-actor typed

**Comment by renatocaval** [comment]
Got another one like this in #112

**Comment by seglo** [comment]
This is happening in #130 as well. I can't reproduce it reliably.

**Comment by patriknw** [comment]
@ennru has a fix for this in Alpakka and will incorporate it in Akka. Nothing we can/should do here in Projections.

**Comment by patriknw** [comment]
Solved in Akka https://github.com/akka/akka/pull/29070
Keeping this issue open until we upgrade.
