### ISSUE TITLE
failed: KafkaToSlickIntegrationSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#109]
Failed in PR validation of https://github.com/akka/akka-projection/pull/80

See attached log
[KafkaToSlickIntegrationSpec.log](https://github.com/akka/akka-projection/files/4608274/KafkaToSlickIntegrationSpec.log)

**Comment by patriknw** [comment]
I marked that test as `pending` so that the PR could be merged

**Comment by patriknw** [comment]
This is still failing
```
[info] - must project a model and Kafka offset map to a slick db exactly once *** FAILED *** (37 seconds, 328 milliseconds)
11944[info]   check - all event type counts are correct 2 was not equal to 3 (KafkaToSlickIntegrationSpec.scala:154)
11945[info]   org.scalatest.exceptions.TestFailedException:
11946[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
11947[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6982)
11948[info]   at akka.projection.kafka.integration.KafkaToSlickIntegrationSpec.assertEventTypeCount$1(KafkaToSlickIntegrationSpec.scala:155)
11949[info]   at akka.projection.kafka.integration.KafkaToSlickIntegrationSpec.$anonfun$new$11(KafkaToSlickIntegrationSpec.scala:163)
```

**Comment by patriknw** [comment]
I marked it as pending again, so I could merge my PR

**Comment by seglo** [comment]
Sorry.  I'll figure this out soon.
