### ISSUE TITLE
Failed: EventSourcedPubSubSpec (SqlServer)

### ISSUE THREAD

**Issue by johanandren** [akka/akka-projection#1160]
https://github.com/akka/akka-projection/actions/runs/9093229073/job/24991679646?pr=1158#step:7:451

```
[info] A R2DBC projection with eventsBySlices source and publish-events (dialect sqlserver)
--> [akka.projection.r2dbc.EventSourcedPubSubSpec: A R2DBC projection with eventsBySlices source and publish-events (dialect sqlserver) must handle all events exactlyOnce] Start of log messages of test that [Failed(java.lang.AssertionError: Timeout (25 seconds) during receiveMessage while waiting for message.)]
[2024-05-15 09:30:51,929] [INFO] [akka.event.slf4j.Slf4jLogger] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-4] - Slf4jLogger started
[2024-05-15 09:30:51,959] [WARN] [akka.persistence.r2dbc.internal.ConnectionFactorySettings$] [] [] [pool-1-thread-1] - The `sqlserver` dialect is currently marked as experimental and not yet production ready.
[2024-05-15 09:30:51,962] [WARN] [akka.persistence.r2dbc.internal.ConnectionFactorySettings$] [] [] [pool-1-thread-1] - The `sqlserver` dialect is currently marked as experimental and not yet production ready.
[2024-05-15 09:30:51,999] [INFO] [akka.actor.testkit.typed.scaladsl.LogCapturing] [] [] [pool-1-thread-1-ScalaTest-running-EventSourcedPubSubSpec] - Logging started for test [akka.projection.r2dbc.EventSourcedPubSubSpec: A R2DBC projection with eventsBySlices source and publish-events (dialect sqlserver) must handle all events exactlyOnce]
[2024-05-15 09:30:52,007] [WARN] [akka.persistence.Persistence] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-7] - No default snapshot store configured! To configure a default snapshot-store plugin set the `akka.persistence.snapshot-store.plugin` key. For details see 'reference.conf'
[2024-05-15 09:30:52,007] [WARN] [akka.persistence.r2dbc.internal.ConnectionFactorySettings$] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-6] - The `sqlserver` dialect is currently marked as experimental and not yet production ready.
[2024-05-15 09:30:52,008] [WARN] [akka.persistence.r2dbc.internal.ConnectionFactorySettings$] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-6] - The `sqlserver` dialect is currently marked as experimental and not yet production ready.
[2024-05-15 09:30:52,008] [DEBUG] [akka.persistence.r2dbc.query.scaladsl.R2dbcReadJournal] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-6] - R2DBC read journal starting up with dialect [sqlserver]
[2024-05-15 09:30:52,016] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-6] - Highest sequence nr for persistenceId [TestEntity-3|p0]: [0]
[2024-05-15 09:30:52,016] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-6] - Highest sequence nr for persistenceId [TestEntity-3|p2]: [0]
[2024-05-15 09:30:52,017] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-6] - Highest sequence nr for persistenceId [TestEntity-3|p1]: [0]
[2024-05-15 09:30:52,027] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-6] - Highest sequence nr for persistenceId [TestEntity-3|p6]: [0]
[2024-05-15 09:30:52,032] [DEBUG] [akka.projection.r2dbc.EventSourcedEndToEndSpec$Persister$] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-6] - Persist [e00001], pid [TestEntity-3|p1], seqNr [1]
[2024-05-15 09:30:52,032] [DEBUG] [akka.projection.r2dbc.EventSourcedEndToEndSpec$Persister$] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-9] - Persist [e00002], pid [TestEntity-3|p2], seqNr [1]
[2024-05-15 09:30:52,032] [DEBUG] [akka.projection.r2dbc.EventSourcedEndToEndSpec$Persister$] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-9] - Persist [e00006], pid [TestEntity-3|p6], seqNr [1]
[2024-05-15 09:30:52,036] [DEBUG] [akka.projection.r2dbc.internal.R2dbcOffsetStore] [] [] [pool-1-thread-1-ScalaTest-running-EventSourcedPubSubSpec] - Offset store [ProjectionId(b2682b6b-ec12-418f-81d7-c0a8a83ffce2, 0-255)] created, with dialect [sqlserver]
[2024-05-15 09:30:52,038] [INFO] [akka.projection.ProjectionBehavior$] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-10] - Starting projection [ProjectionId(b2682b6b-ec12-418f-81d7-c0a8a83ffce2, 0-255)]
[2024-05-15 09:30:52,040] [DEBUG] [akka.projection.r2dbc.internal.R2dbcOffsetStore] [] [] [pool-1-thread-1-ScalaTest-running-EventSourcedPubSubSpec] - Offset store [ProjectionId(b2682b6b-ec12-418f-81d7-c0a8a83ffce2, 256-511)] created, with dialect [sqlserver]
[2024-05-15 09:30:52,040] [INFO] [akka.projection.ProjectionBehavior$] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-4] - Starting projection [ProjectionId(b2682b6b-ec12-418f-81d7-c0a8a83ffce2, 256-511)]
[2024-05-15 09:30:52,042] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-4] - Highest sequence nr for persistenceId [TestEntity-3|p4]: [0]
[2024-05-15 09:30:52,042] [DEBUG] [akka.projection.r2dbc.EventSourcedEndToEndSpec$Persister$] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-8] - Persist [e00004], pid [TestEntity-3|p4], seqNr [1]
[2024-05-15 09:30:52,042] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-4] - Highest sequence nr for persistenceId [TestEntity-3|p15]: [0]
[2024-05-15 09:30:52,042] [DEBUG] [akka.projection.r2dbc.internal.R2dbcOffsetStore] [] [] [pool-1-thread-1-ScalaTest-running-EventSourcedPubSubSpec] - Offset store [ProjectionId(b2682b6b-ec12-418f-81d7-c0a8a83ffce2, 512-767)] created, with dialect [sqlserver]
[2024-05-15 09:30:52,042] [INFO] [akka.projection.ProjectionBehavior$] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-9] - Starting projection [ProjectionId(b2682b6b-ec12-418f-81d7-c0a8a83ffce2, 512-767)]
[2024-05-15 09:30:52,042] [DEBUG] [akka.projection.r2dbc.internal.R2dbcOffsetStore] [] [] [pool-1-thread-1-ScalaTest-running-EventSourcedPubSubSpec] - Offset store [ProjectionId(b2682b6b-ec12-418f-81d7-c0a8a83ffce2, 768-1023)] created, with dialect [sqlserver]
[2024-05-15 09:30:52,043] [INFO] [akka.projection.ProjectionBehavior$] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-10] - Starting projection [ProjectionId(b2682b6b-ec12-418f-81d7-c0a8a83ffce2, 768-1023)]
[2024-05-15 09:30:52,049] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-11] - Highest sequence nr for persistenceId [TestEntity-3|p5]: [0]
[2024-05-15 09:30:52,050] [DEBUG] [akka.projection.r2dbc.EventSourcedEndToEndSpec$Persister$] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-11] - Persist [e00005], pid [TestEntity-3|p5], seqNr [1]
[2024-05-15 09:30:52,056] [INFO] [akka.actor.DeadLetterActorRef] [akka://EventSourcedPubSubSpec] [akkaDeadLetter] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-4] - Message [akka.persistence.query.typed.EventEnvelope] wrapped in [akka.actor.Dropped] to Actor[akka://EventSourcedPubSubSpec/deadLetters] was not delivered. [1] dead letters encountered. If this is not an expected behavior then Actor[akka://EventSourcedPubSubSpec/deadLetters] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2024-05-15 09:30:52,056] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-12] - Wrote [1] events for persistenceId [TestEntity-3|p2]
[2024-05-15 09:30:52,056] [INFO] [akka.actor.DeadLetterActorRef] [akka://EventSourcedPubSubSpec] [akkaDeadLetter] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-10] - Message [akka.persistence.query.typed.EventEnvelope] wrapped in [akka.actor.Dropped] to Actor[akka://EventSourcedPubSubSpec/deadLetters] was not delivered. [2] dead letters encountered. If this is not an expected behavior then Actor[akka://EventSourcedPubSubSpec/deadLetters] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2024-05-15 09:30:52,056] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-11] - Wrote [1] events for persistenceId [TestEntity-3|p6]
[2024-05-15 09:30:52,058] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-9] - Highest sequence nr for persistenceId [TestEntity-3|p8]: [0]
[2024-05-15 09:30:52,058] [DEBUG] [akka.projection.r2dbc.EventSourcedEndToEndSpec$Persister$] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-9] - Persist [e00008], pid [TestEntity-3|p8], seqNr [1]
[2024-05-15 09:30:52,080] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-11] - Highest sequence nr for persistenceId [TestEntity-3|p3]: [0]
[2024-05-15 09:30:52,080] [DEBUG] [akka.projection.r2dbc.EventSourcedEndToEndSpec$Persister$] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-11] - Persist [e00003], pid [TestEntity-3|p3], seqNr [1]
[2024-05-15 09:30:52,086] [DEBUG] [akka.projection.r2dbc.internal.R2dbcOffsetStore] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-12] - readTimestampOffset state with [0] persistenceIds, oldest [1970-01-01T00:00:00Z], latest [1970-01-01T00:00:00Z]
[2024-05-15 09:30:52,091] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-12] - Wrote [1] events for persistenceId [TestEntity-3|p4]
[2024-05-15 09:30:52,091] [INFO] [akka.actor.DeadLetterActorRef] [akka://EventSourcedPubSubSpec] [akkaDeadLetter] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-11] - Message [akka.persistence.query.typed.EventEnvelope] wrapped in [akka.actor.Dropped] to Actor[akka://EventSourcedPubSubSpec/deadLetters] was not delivered. [3] dead letters encountered. If this is not an expected behavior then Actor[akka://EventSourcedPubSubSpec/deadLetters] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2024-05-15 09:30:52,097] [DEBUG] [akka.projection.r2dbc.internal.R2dbcOffsetStore] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-12] - readTimestampOffset state with [0] persistenceIds, oldest [1970-01-01T00:00:00Z], latest [1970-01-01T00:00:00Z]
[2024-05-15 09:30:52,100] [DEBUG] [akka.projection.r2dbc.internal.R2dbcOffsetStore] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-11] - readTimestampOffset state with [0] persistenceIds, oldest [1970-01-01T00:00:00Z], latest [1970-01-01T00:00:00Z]
[2024-05-15 09:30:52,108] [DEBUG] [akka.projection.r2dbc.internal.R2dbcOffsetStore] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-11] - readTimestampOffset state with [0] persistenceIds, oldest [1970-01-01T00:00:00Z], latest [1970-01-01T00:00:00Z]
[2024-05-15 09:30:52,115] [DEBUG] [akka.persistence.r2dbc.query.scaladsl.R2dbcReadJournal] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-11] - Starting eventsBySlices query from slices [768 - 1023], from time [1970-01-01T00:00:00Z].
[2024-05-15 09:30:52,116] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-12] - Highest sequence nr for persistenceId [TestEntity-3|p12]: [0]
[2024-05-15 09:30:52,117] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-4] - Highest sequence nr for persistenceId [TestEntity-3|p19]: [0]
[2024-05-15 09:30:52,117] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-12] - Highest sequence nr for persistenceId [TestEntity-3|p7]: [0]
[2024-05-15 09:30:52,117] [DEBUG] [akka.projection.r2dbc.EventSourcedEndToEndSpec$Persister$] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-12] - Persist [e00007], pid [TestEntity-3|p7], seqNr [1]
[2024-05-15 09:30:52,119] [DEBUG] [akka.persistence.r2dbc.query.scaladsl.R2dbcReadJournal] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-4] - Starting eventsBySlices query from slices [512 - 767], from time [1970-01-01T00:00:00Z].
[2024-05-15 09:30:52,120] [DEBUG] [akka.persistence.r2dbc.query.scaladsl.R2dbcReadJournal] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-9] - Starting eventsBySlices query from slices [256 - 511], from time [1970-01-01T00:00:00Z].
[2024-05-15 09:30:52,122] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-10] - Wrote [1] events for persistenceId [TestEntity-3|p5]
[2024-05-15 09:30:52,122] [INFO] [akka.actor.DeadLetterActorRef] [akka://EventSourcedPubSubSpec] [akkaDeadLetter] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-10] - Message [akka.persistence.query.typed.EventEnvelope] wrapped in [akka.actor.Dropped] to Actor[akka://EventSourcedPubSubSpec/deadLetters] was not delivered. [4] dead letters encountered. If this is not an expected behavior then Actor[akka://EventSourcedPubSubSpec/deadLetters] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2024-05-15 09:30:52,123] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-8] - Wrote [1] events for persistenceId [TestEntity-3|p8]
[2024-05-15 09:30:52,131] [INFO] [akka.actor.DeadLetterActorRef] [akka://EventSourcedPubSubSpec] [akkaDeadLetter] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-10] - Message [akka.persistence.query.typed.EventEnvelope] wrapped in [akka.actor.Dropped] to Actor[akka://EventSourcedPubSubSpec/deadLetters] was not delivered. [5] dead letters encountered. If this is not an expected behavior then Actor[akka://EventSourcedPubSubSpec/deadLetters] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2024-05-15 09:30:52,132] [DEBUG] [akka.persistence.r2dbc.query.scaladsl.R2dbcReadJournal] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-7] - Starting eventsBySlices query from slices [0 - 255], from time [1970-01-01T00:00:00Z].
[2024-05-15 09:30:52,135] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-12] - Highest sequence nr for persistenceId [TestEntity-3|p10]: [0]
[2024-05-15 09:30:52,135] [DEBUG] [akka.projection.r2dbc.EventSourcedEndToEndSpec$Persister$] [akka://EventSourcedPubSubSpec] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-12] - Persist [e00010], pid [TestEntity-3|p10], seqNr [1]
[2024-05-15 09:30:52,136] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-12] - Highest sequence nr for persistenceId [TestEntity-3|p16]: [0]
[2024-05-15 09:30:52,139] [DEBUG] [akka.persistence.r2dbc.internal.sqlserver.SqlServerJournalDao] [] [] [EventSourcedPubSubSpec-akka.actor.default-dispatcher-10] - Highest sequence nr for persistenceId [TestEntity-3|p18]: [0]
[info] - must handle all events exactlyOnce *** FAILED *** (28 seconds, 297 milliseconds)
[info]   java.lang.AssertionError: Timeout (25 seconds) during receiveMessage while waiting for message.
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessage_internal$1(TestProbeImpl.scala:182)
[info]   at scala.Option.getOrElse(Option.scala:201)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessage_internal(TestProbeImpl.scala:182)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessage(TestProbeImpl.scala:179)
[info]   at akka.projection.r2dbc.EventSourcedPubSubSpec.$anonfun$expectProcessed$2(EventSourcedPubSubSpec.scala:132)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
[info]   at akka.projection.r2dbc.EventSourcedPubSubSpec.expectProcessed(EventSourcedPubSubSpec.scala:129)
[info]   at akka.projection.r2dbc.EventSourcedPubSubSpec.$anonfun$new$2(EventSourcedPubSubSpec.scala:183)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1240)
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:79)
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:77)
[info]   at akka.projection.r2dbc.EventSourcedPubSubSpec.withFixture(EventSourcedPubSubSpec.scala:80)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1238)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1250)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1250)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1232)
[info]   at akka.projection.r2dbc.EventSourcedPubSubSpec.runTest(EventSourcedPubSubSpec.scala:80)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1309)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[info]   at scala.collection.immutable.List.foreach(List.scala:334)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
[info]   at scala.collection.immutable.List.foreach(List.scala:334)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1309)
[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1308)
[info]   at akka.projection.r2dbc.EventSourcedPubSubSpec.runTests(EventSourcedPubSubSpec.scala:80)
[info]   at org.scalatest.Suite.run(Suite.scala:1114)
[info]   at org.scalatest.Suite.run$(Suite.scala:1096)
[info]   at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.org$scalatest$BeforeAndAfterAll$$super$run(ScalaTestWithActorTestKit.scala:31)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.projection.r2dbc.EventSourcedPubSubSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(EventSourcedPubSubSpec.scala:80)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/9158974621/job/25179949684?pr=1165#step:7:1120

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/13319485275/job/37201171302#step:7:8029
