### ISSUE TITLE
Failed: R2dbcTimestampOffsetStoreSpec (SqlServer)

### ISSUE THREAD

**Issue by johanandren** [akka/akka-projection#1163]
https://github.com/akka/akka-projection/actions/runs/9094676912/job/24996265687?pr=1158#step:7:134

```
[info] - must delete many old records *** FAILED *** (3 seconds, 247 milliseconds)
[info]   The future returned an exception of type: java.lang.NullPointerException, with message: Cannot invoke "java.time.LocalDateTime.atZone(java.time.ZoneId)" because "timestamp" is null. (R2dbcTimestampOffsetStoreSpec.scala:1013)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at akka.projection.r2dbc.R2dbcTimestampOffsetStoreSpec.$anonfun$new$26(R2dbcTimestampOffsetStoreSpec.scala:1013)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/9158974621/job/25178411474?pr=1165#step:7:421
