### ISSUE TITLE
failed: FilterStageSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#1234]
https://github.com/akka/akka-projection/actions/runs/11513524157/job/32050382735?pr=1171#step:6:643

```
[info] - must replay from ReplayReq with RES ReplicaId *** FAILED *** (145 milliseconds)
[info]   java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnNext(EventEnvelope(TimestampOffset(2024-10-25T07:08:12.931244Z, 1970-01-01T00:00:00Z, Map(EntityA|a|B -> 1)),EntityA|a|B,1,java.lang.String,1729840092931,,EntityA,247,false,,[])),Actor[akka://FilterStageSpec/deadLetters]) after 49 millis
[info]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:751)
[info]   at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:724)
[info]   at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:723)
[info]   at akka.testkit.TestKit.expectNoMessage(TestKit.scala:955)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNoMessage(StreamTestKit.scala:633)
[info]   at akka.projection.grpc.internal.FilterStageSpec$$anon$7.<init>(FilterStageSpec.scala:292)
[info]   at akka.projection.grpc.internal.FilterStageSpec.$anonfun$new$15(FilterStageSpec.scala:272)
```

**Comment by patriknw** [comment]
this was part of the PR changes, and fixed there
