### ISSUE TITLE
[failed] akka.projection.kafka.KafkaSourceProviderSpec

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-projection#247]
https://travis-ci.com/github/akka/akka-projection/jobs/350536302
```
<-- [akka.projection.kafka.KafkaSourceProviderSpec: KafkaSourceProviderSpec must resume from provided offsets] End of log messages of test that [Failed(java.util.concurrent.TimeoutException)]
[info] - must resume from provided offsets *** FAILED *** (10 seconds, 50 milliseconds)
[info]   java.util.concurrent.TimeoutException:
[info]   at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:108)
[info]   at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:272)
[info]   at akka.kafka.testkit.internal.KafkaTestKit.createTopic(KafkaTestKit.scala:180)
```

**Comment by seglo** [comment]
This was addressed in #380
