### ISSUE TITLE
[failed] akka.projection.kafka.integration.KafkaToSlickIntegrationSpec

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-projection#248]
https://travis-ci.com/github/akka/akka-projection/jobs/350536302

See also #247 

```
[info] - must project a model and Kafka offset map to a slick db exactly once *** FAILED *** (13 seconds, 348 milliseconds)
[info]   java.util.concurrent.TimeoutException:
[info]   at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:108)
[info]   at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:272)
[info]   at akka.kafka.testkit.internal.KafkaTestKit.createTopic(KafkaTestKit.scala:180)
[info]   at akka.kafka.testkit.internal.KafkaTestKit.createTopic$(KafkaTestKit.scala:175)
[info]   at akka.kafka.testkit.scaladsl.KafkaSpec.createTopic(KafkaSpec.scala:35)
[info]   at akka.kafka.testkit.internal.KafkaTestKit.createTopic(KafkaTestKit.scala:166)
[info]   at akka.kafka.testkit.internal.KafkaTestKit.createTopic$(KafkaTestKit.scala:160)
[info]   at akka.kafka.testkit.scaladsl.KafkaSpec.createTopic(KafkaSpec.scala:35)
[info]   at akka.kafka.testkit.internal.KafkaTestKit.createTopic(KafkaTestKit.scala:153)
[info]   at akka.kafka.testkit.internal.KafkaTestKit.createTopic$(KafkaTestKit.scala:152)
```

**Comment by seglo** [comment]
This was addressed in #380
