### ISSUE TITLE
failed: ProjectionTestKitSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#285]
https://travis-ci.com/github/akka/akka-projection/jobs/353908714

```
[info] ProjectionTestKitSpec:
351[info] ProjectionTestKit
352[info] - must assert progress of a projection (223 milliseconds)
353[info] - must retry assertion function until it succeeds within a max timeout (1 second, 319 milliseconds)
354[info] - must abort retryAndFail when retrying (3 seconds, 211 milliseconds)
355[info] - must retry assertion function and fail when timeout expires (917 milliseconds)
356[info] ProjectionTestKitTest:
357[info] - failureInsideStreamPropagatesToTestkit
358[info] - must failure inside Projection propagates to TestKit (2 seconds, 915 milliseconds)
359[info] - failureInsideProjectionPropagatesToTestkit
360[info] - assertProgressOfAProjection
361[info] - must failure inside Stream propagates to TestKit (2 seconds, 920 milliseconds)
362[info] - must run a projection with a TestSink (68 milliseconds)
363[info] Compiling 2 Scala sources to /home/travis/build/akka/akka-projection/akka-projection-slick/target/scala-2.12/test-classes ...
364[info] - retryAssertionFunctionAndFailWhenTimeoutExpires
365[info] - runAProjectionWithATestSink
366[info] - retryAssertionFunctionUntilItSucceedsWithinAMaxTimeout *** FAILED ***
367[info]   org.junit.ComparisonFailure: expected:<1-2-3-4-5[]> but was:<1-2-3-4-5[-6]>
368[info]   at org.junit.Assert.assertEquals(Assert.java:115)
369[info]   at org.junit.Assert.assertEquals(Assert.java:144)
370[info]   at akka.projection.testkit.javadsl.ProjectionTestKitTest.lambda$retryAssertionFunctionUntilItSucceedsWithinAMaxTimeout$a6168c43$1(ProjectionTestKitTest.java:78)
371[info]   at akka.projection.testkit.javadsl.ProjectionTestKit.$anonfun$runInternal$1(ProjectionTestKit.scala:109)
372[info]   at akka.projection.testkit.javadsl.ProjectionTestKit.$anonfun$runInternal$1$adapted(ProjectionTestKit.scala:109)
373[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$awaitAssert$1(TestProbeImpl.scala:343)
374[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.poll$1(TestProbeImpl.scala:361)
375[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert_internal(TestProbeImpl.scala:378)
376[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert(TestProbeImpl.scala:343)
377[info]   at akka.projection.testkit.javadsl.ProjectionTestKit.runInternal(ProjectionTestKit.scala:109)
378[info]   at akka.projection.testkit.javadsl.ProjectionTestKit.run(ProjectionTestKit.scala:73)
379[info]   at akka.projection.testkit.javadsl.ProjectionTestKitTest.retryAssertionFunctionUntilItSucceedsWithinAMaxTimeout(ProjectionTestKitTest.java:77)
```

**Comment by renatocaval** [comment]
fixed in https://github.com/akka/akka-projection/pull/303
