### ISSUE TITLE
failed: LifecycleMetricSpec - count a start and a stop

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#293]
https://travis-ci.com/github/akka/akka-projection/jobs/353931645

```
[info]   - must count a start and a stop *** FAILED *** (69 milliseconds)
431[info]     0 was not equal to 1 (LifecycleMetricSpec.scala:43)
432[info]     org.scalatest.exceptions.TestFailedException:
433[info]     at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)
434[info]     at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6778)
435[info]     at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6822)
436[info]     at akka.projection.internal.metrics.LifecycleMetricAtLeastOnceSpec.$anonfun$new$4(LifecycleMetricSpec.scala:43)
437[info]     at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
438[info]     at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
439[info]     at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
440[info]     at org.scalatest.Transformer.apply(Transformer.scala:22)
441[info]     at org.scalatest.Transformer.apply(Transformer.scala:20)
442[info]     at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
443[info]     at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:54)
444[info]     at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:52)
445[info]     at akka.projection.internal.metrics.tools.InternalProjectionStateMetricsSpec.withFixture(InternalProjectionStateMetricsSpec.scala:55)
```

**Comment by ignasi35** [comment]
fixed in #298
