### ISSUE TITLE
CassandraProjectionSpec: must fail after retrying when using RecoveryStrategy.retryAndFail

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-projection#300]
https://travis-ci.com/github/akka/akka-projection/jobs/355325704

```
[info] - must fail after retrying when using RecoveryStrategy.retryAndFail *** FAILED *** (3 seconds, 47 milliseconds)

[info]   Expected exception akka.actor.testkit.typed.TestException to be thrown, but no exception was thrown (CassandraProjectionSpec.scala:509)

[info]   org.scalatest.exceptions.TestFailedException:

[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)

[info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)

[info]   at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.newAssertionFailedException(ScalaTestWithActorTestKit.scala:31)

[info]   at org.scalatest.Assertions.intercept(Assertions.scala:766)

[info]   at org.scalatest.Assertions.intercept$(Assertions.scala:746)

[info]   at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.intercept(ScalaTestWithActorTestKit.scala:31)

[info]   at akka.projection.cassandra.CassandraProjectionSpec.$anonfun$new$61(CassandraProjectionSpec.scala:509)

[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)

[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)

[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)

[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)

[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka-projection/runs/5185067428?check_suite_focus=true#step:6:496
