### ISSUE TITLE
ClassCastException after restart

### ISSUE THREAD

**Issue by bluedigits** [akka/akka-projection#305]
### Versions used 

Akka version: 2.6.6

Akka Projection version: 0.2 and 0.3

### Expected Behavior

The Akka Projection should successfully resume from previous run.

### Actual Behavior

After restarting the Akka Projection it fails when reading the offset from the `AKKA_PROJECTION_OFFSET_STORE` table. This happens with H2 in server mode having persistency as well as with MySQL. I was wondering if it's only due to my custom implementation, but it happens also with the `KafkaDocExample` from the given examples when using SlickProjections.

### Relevant logs

```
2020-07-01 12:36:20 WARN  a.s.s.RestartWithBackoffSource RestartWithBackoffSource(akka://projector) Restarting graph due to failure. stack_trace: 
akka.kafka.ConsumerFailed: [8a9c9#1]  Failed to fetch offset for partitions: users-0.
	at akka.kafka.internal.SubSourceLogic.$anonfun$partitionAssignedCB$2(SubSourceLogic.scala:134)
	at akka.kafka.internal.SubSourceLogic.$anonfun$partitionAssignedCB$2$adapted(SubSourceLogic.scala:129)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.RuntimeException: External offsets could not be retrieved
	at akka.projection.kafka.internal.KafkaSourceProviderImpl$$anonfun$$nestedInanonfun$getOffsetsOnAssign$2$1.applyOrElse(KafkaSourceProviderImpl.scala:124)
	at akka.projection.kafka.internal.KafkaSourceProviderImpl$$anonfun$$nestedInanonfun$getOffsetsOnAssign$2$1.applyOrElse(KafkaSourceProviderImpl.scala:123)
	at scala.util.Failure.recover(Try.scala:233)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:450)
	... 11 more
Caused by: java.lang.ClassCastException: akka.projection.MergeableOffset cannot be cast to akka.projection.kafka.GroupOffsets
	at akka.projection.kafka.internal.KafkaSourceProviderImpl.$anonfun$getOffsetsOnAssign$3(KafkaSourceProviderImpl.scala:115)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
	... 11 more
```

### Reproducible Test Case

Will provide later, if necessary

**Comment by renatocaval** [comment]
Thanks @bluedigits for reporting this. 

I will try to reproduce it using the `KafkaDocExample` and let you know in case we need a reproducer.

**Comment by bluedigits** [comment]
You can reproduce it using the `KafkaDocExample` doing the following:
- Use SlickProjections instead of JdbcProjections
- Remove the Hibernate sessions

**Comment by renatocaval** [comment]
For the record, I look into it on detail and the problem is that the projections source provider created for Kafka is typed to `GroupOffsets`, this info is then passed to the offset store and when reading back serialized data from the table it tries to cast it. 

https://github.com/akka/akka-projection/blob/4f231f529aed0915c090989018ecb04c46ef20fa/akka-projection-slick/src/main/scala/akka/projection/slick/internal/SlickOffsetStore.scala#L54

The problem is that when we see many offsets for the same projection, we keep the underlying type (eg: Long), but we consider that the outer type to be `MergeableOffset` so we build a `MergeableOffset`. 

But the expected outer type is `GroupOffsets` and then the cast fails. 

I tried to make `GroupOffsets` a type alias of `MergeableOffset[TopicPartitionKey, Long]` instead of extending it, but type inference breaks between Java and Scala API. Java API sees the `scala.Long` as `Object`. 

Anyway, we will need to revise it. I will continue tomorrow.
