### ISSUE TITLE
Fail: TestContainer failing to pull image for MS SQL Server

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#318]
Happend on PR build: 
https://travis-ci.com/github/akka/akka-projection/jobs/358432955#L548

```scala
 akka.projection.slick.MSSQLServerSlickOffsetStoreSpec *** ABORTED *** (10 milliseconds)
[info]   org.testcontainers.containers.ContainerLaunchException: Container startup failed
[info]   at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:322)
[info]   at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302)
[info]   at com.dimafeng.testcontainers.SingleContainer.start(Container.scala:46)
[info]   at akka.projection.slick.SlickOffsetStoreSpec$MSSQLServerSpecConfig.<init>(SlickOffsetStoreSpec.scala:131)
[info]   at akka.projection.slick.MSSQLServerSlickOffsetStoreSpec.<init>(SlickOffsetStoreSpec.scala:169)
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[info]   at java.base/java.lang.Class.newInstance(Class.java:584)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:450)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:139)
[info]   at sbt.TestRunner.run(TestFramework.scala:154)
[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:317)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:277)
[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:317)
[info]   at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:317)
[info]   at sbt.TestFunction.apply(TestFramework.scala:329)
[info]   at sbt.Tests$.$anonfun$toTask$1(Tests.scala:311)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[info]   at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[info]   at sbt.Execute.work(Execute.scala:290)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:834)
[info]   Cause: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageNameFuture=java.util.concurrent.CompletableFuture@e8f9398[Completed normally], imagePullPolicy=DefaultPullPolicy(), dockerClient=LazyDockerClient.INSTANCE)
```

**Comment by seglo** [comment]
This may have been addressed in #380 if it was due to lag when downloading multiple docker images in parallel.

It hasn't been reported since, so it's probably safe to close.
