### ISSUE TITLE
Fail: Kafka container not starting

### ISSUE THREAD

**Issue by octonato** [akka/akka-projection#329]
Stack trace reduced for conciseness

```scala
[info] akka.projection.kafka.integration.KafkaToSlickIntegrationSpec *** ABORTED *** (1 minute, 37 seconds)
[info]   java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.testcontainers.containers.ContainerLaunchException: Container startup failed
[info]   at akka.kafka.testkit.internal.KafkaContainerCluster.start(KafkaContainerCluster.java:147)
[info]   at akka.kafka.testkit.internal.TestcontainersKafka$Spec.startKafka(TestcontainersKafka.scala:65)
...
[info]   Cause: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
[info]   at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
[info]   at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:315)
[info]   at akka.kafka.testkit.internal.AlpakkaKafkaContainer.doStart(AlpakkaKafkaContainer.java:143)
[info]   at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302)
[info]   at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
[info]   at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:834)
[info]   Cause: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
[info]   at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:485)
[info]   at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:317)
[info]   at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
[info]   at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:315)
[info]   at akka.kafka.testkit.internal.AlpakkaKafkaContainer.doStart(AlpakkaKafkaContainer.java:143)
[info]   at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302)
[info]   at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
[info]   at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:834)
[info]   Cause: java.lang.IllegalStateException: Container exited with code 1
[info]   at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:457)
[info]   at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:317)
[info]   at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
[info]   at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:315)
[info]   at akka.kafka.testkit.internal.AlpakkaKafkaContainer.doStart(AlpakkaKafkaContainer.java:143)
[info]   at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302)
[info]   at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
[info]   at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by seglo** [comment]
Is there a build associated with the failure?  If you're seeing this consistently while running local a common cause of failure I've observed is that the docker network wasn't cleaned up correctly after a test is aborted for some reason.  That cause is usually buried deep in the stack trace.  I get it once in awhile and then need to prune unused docker networks to resolve the problem.

**Comment by renatocaval** [comment]
No, I saw it on a PR build. I didn't link here because the link gets invalidate when we retriggered it.

**Comment by ignasi35** [comment]
> [...] a common cause of container startup failure I've observed is that the docker network wasn't cleaned up correctly after a test is aborted for some reason[...]

I've just observed a similar failure as part of #332 after we disabled [`parallelExecution`](https://github.com/akka/akka-projection/pull/332/commits/bddff350c0dd3521e346517453d6d92c230ea573). I noticed the first test in `akka-projection-kafka` succeeded but the other two failed.

Put another way, I wonder if on Travis, the test execution is too fast for docker so once the first test completes, the container is dropped, but then the second test comes in and fails to create a new container because the first one has complete the stop/removal.

**Comment by ignasi35** [comment]
On a call, we considered trying out something: if we put all the test code into a single test class, then there'll be no stop-then-start transitions.

**Comment by seglo** [comment]
> On a call, we considered trying out something: if we put all the test code into a single test class, then there'll be no stop-then-start transitions.

There's an easier way to validate this theory.  Alpakka Kafka has another testcontainer testkit trait `TestcontainersKafkaLike`.  The implementation uses a singleton instance of the testcontainer.  This might be good if you have a lot of Kafka tests and want to keep the containers around the entire test run to reduce the startup/shutdown costs, but I thought it might be better to spin up the containers as needed so they don't take up memory for the rest of the test run.

**Comment by seglo** [comment]
This was addressed in #380

**Comment by seglo** [comment]
Still happening occasionally

https://travis-ci.com/github/akka/akka-projection/jobs/393183540#L670
