### ISSUE TITLE
Failed: recover a projection from a previously saved offset

### ISSUE THREAD

**Issue by seglo** [akka/akka-projection#341]
This test doesn't seem to work anymore and consistently fails.  Requires investigation.  Ignored for now.

```
check - all event type counts are correct 6 was not equal to 3
ScalaTestFailureLocation: akka.projection.kafka.integration.KafkaToSlickIntegrationSpec at (KafkaToSlickIntegrationSpec.scala:267)
Expected :3
Actual   :check - all event type counts are correct 6
<Click to see difference>

org.scalatest.exceptions.TestFailedException: check - all event type counts are correct 6 was not equal to 3
	at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
	at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6982)
	at akka.projection.kafka.integration.KafkaToSlickIntegrationSpec.assertEventTypeCount$1(KafkaToSlickIntegrationSpec.scala:267)
	at akka.projection.kafka.integration.KafkaToSlickIntegrationSpec.$anonfun$assertEventTypeCount$2(KafkaToSlickIntegrationSpec.scala:275)
	at org.scalatest.Assertions.withClue(Assertions.scala:1065)
	at org.scalatest.Assertions.withClue$(Assertions.scala:1052)
	at akka.projection.kafka.KafkaSpecBase.withClue(KafkaSpecBase.scala:26)
	at akka.projection.kafka.integration.KafkaToSlickIntegrationSpec.assertEventTypeCount(KafkaToSlickIntegrationSpec.scala:270)
	at akka.projection.kafka.integration.KafkaToSlickIntegrationSpec.$anonfun$new$15(KafkaToSlickIntegrationSpec.scala:245)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at akka.actor.testkit.typed.internal.TestProbeImpl.poll$1(TestProbeImpl.scala:361)
	at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert_internal(TestProbeImpl.scala:378)
	at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert(TestProbeImpl.scala:334)
	at akka.projection.testkit.scaladsl.ProjectionTestKit.runInternal(ProjectionTestKit.scala:103)
	at akka.projection.testkit.scaladsl.ProjectionTestKit.run(ProjectionTestKit.scala:68)
	at akka.projection.kafka.integration.KafkaToSlickIntegrationSpec.$anonfun$new$11(KafkaToSlickIntegrationSpec.scala:244)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
	at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:54)
	at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:52)
	at akka.projection.kafka.KafkaSpecBase.withFixture(KafkaSpecBase.scala:26)
	at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)
	at akka.projection.kafka.KafkaSpecBase.org$scalatest$BeforeAndAfterEach$$super$runTest(KafkaSpecBase.scala:26)
	at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:234)
	at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:227)
	at akka.projection.kafka.KafkaSpecBase.runTest(KafkaSpecBase.scala:26)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)
	at akka.projection.kafka.KafkaSpecBase.runTests(KafkaSpecBase.scala:26)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at akka.projection.kafka.KafkaSpecBase.org$scalatest$BeforeAndAfterAll$$super$run(KafkaSpecBase.scala:26)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at akka.projection.kafka.KafkaSpecBase.org$scalatest$wordspec$AnyWordSpecLike$$super$run(KafkaSpecBase.scala:26)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)
	at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)
	at akka.projection.kafka.KafkaSpecBase.run(KafkaSpecBase.scala:26)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1320)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1314)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1314)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
```

**Comment by renatocaval** [comment]
Does it fail locally for you? 

Last week we reached a point where none of the Kafka tests where passing in Travis. I did a few wild merges, but always after building locally using JDK8/11 and Scala 2.12/2.13. I never saw this failing locally.

**Comment by seglo** [comment]
Yes, it's failing locally for me, and consistently with the same result.  Probably an easy fix.
