### ISSUE TITLE
`ProjectionTestKit` should spawn Behaviors when using `ActorHandler`

### ISSUE THREAD

**Issue by tPl0ch** [akka/akka-projection#416]
### Versions used 

Akka version: 2.6.8
Akka Projection: 1.0.0-RC3
Akka Projection Testkit: 1.0.0-RC3

### Expected Behavior

Running the `TestProjection` should spawn an `ActorHandler` as described in https://doc.akka.io/docs/akka-projection/current/actor.html

> The `Behavior` given to the `ActorHandler` is spawned automatically by the Projection and each envelope is sent to the actor with ask. The actor is supposed to send a response message to the `replyTo` when it has completed the processing of the envelope. The Try indicates if the processing was successful or failed.

### Actual Behavior

Since the Behavior is not spawned and [`ActorHandlerInit.setActor`](https://github.com/akka/akka-projection/blob/56eb13f7a4e127d16d43b4317c8de04a1df3bab9/akka-projection-core/src/main/scala/akka/projection/internal/ActorHandlerInit.scala#L21) is not called, the call to [`ActorHandlerInit.getActor`](https://github.com/akka/akka-projection/blob/56eb13f7a4e127d16d43b4317c8de04a1df3bab9/akka-projection-core/src/main/scala/akka/projection/internal/ActorHandlerInit.scala#L25) results in an Exception being thrown.

### Relevant logs

```
2020-09-03T17:07:53.126 level=ERROR logger=a.p.t.i.TestInternalProjectionState | [projectionId-0] Failed to process envelope with offset [Sequence(0)]. Projection will stop as defined by recovery strategy.
java.lang.IllegalStateException: Actor not started, please report issue at https://github.com/akka/akka-projection/issues
    at akka.projection.internal.ActorHandlerInit.getActor(ActorHandlerInit.scala:30)
    at akka.projection.internal.ActorHandlerInit.getActor$(ActorHandlerInit.scala:25)
    at akka.projection.scaladsl.ActorHandler.getActor(ActorHandler.scala:24)
    at akka.projection.scaladsl.ActorHandler.process(ActorHandler.scala:41)
    at akka.projection.internal.InternalProjectionState.$anonfun$atLeastOnceProcessing$2(InternalProjectionState.scala:132)
    at akka.projection.internal.HandlerRecoveryImpl.$anonfun$applyRecovery$1(HandlerRecoveryImpl.scala:69)
    at akka.projection.internal.HandlerRecoveryImpl.applyRecovery(HandlerRecoveryImpl.scala:90)
    at akka.projection.internal.InternalProjectionState.$anonfun$atLeastOnceProcessing$1(InternalProjectionState.scala:140)
    at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1400)
    at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541)
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:759)
    at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:753)
    at akka.actor.Actor.aroundPreStart(Actor.scala:548)
    at akka.actor.Actor.aroundPreStart$(Actor.scala:548)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:691)
    at akka.actor.ActorCell.create(ActorCell.scala:641)
    at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
    at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
    at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
    at akka.dispatch.Mailbox.run(Mailbox.scala:230)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

### Reproducible Test Case

I believe any run of the `ProjectionTestKit` with an `ActorHandler` will currently result in this Exception, so coming up with a simple test case should be easy (unfortunately I don't have time right now to simplify our use case).

**Comment by seglo** [comment]
Thanks for the report @tPl0ch. I put up a PR for this to be fixed in 1.0.0.

**Comment by tPl0ch** [comment]
@seglo Is the 1.0.0 release already scheduled? And if it is do you know when this will happen?

**Comment by renatocaval** [comment]
@tPl0ch, it's scheduled for very soon. Somewhere next week.

**Comment by patriknw** [comment]
Thanks for reporting @tPl0ch
