### ISSUE TITLE
Failed: JdbcProjectionTest atLeastOnceShouldRestartFromPreviousOffset

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-projection#465]
I've seen this on a PR build. I manually restarted the job to get the PR forward.

related to #397 

```
--> [akka.projection.jdbc.JdbcProjectionTest: atLeastOnceShouldRestartFromPreviousOffset] Start of log messages of test that failed with expected:<abc|def|[ghi|]> but was:<abc|def|[]>
[2020-10-08 11:56:40,811] [DEBUG] [JdbcProjectionTest] [] [pool-18-thread-34] - Starting ActorTestKit MDC: {}
[2020-10-08 11:56:40,812] [INFO] [akka.actor.testkit.typed.javadsl.LogCapturing] [] [pool-18-thread-34] - Logging started for test [akka.projection.jdbc.JdbcProjectionTest: atLeastOnceShouldRestartFromPreviousOffset] MDC: {}
[2020-10-08 11:56:40,847] [ERROR] [akka.projection.jdbc.internal.JdbcProjectionImpl$JdbcInternalProjectionState] [] [JdbcProjectionTest-akka.actor.default-dispatcher-7] - [5dab2ace-3d20-4f8c-b6be-44f79efe6856-00] Failed to process envelope with offset [4]. Projection will stop as defined by recovery strategy. MDC: {akkaAddress=akka://JdbcProjectionTest, sourceThread=JdbcProjectionTest-akka.actor.default-dispatcher-7, akkaSource=JdbcProjectionImpl$JdbcInternalProjectionState(akka://JdbcProjectionTest), sourceActorSystem=JdbcProjectionTest, akkaTimestamp=11:56:40.844UTC}
java.lang.RuntimeException: fail on envelope with offset: [4]
	at akka.projection.jdbc.JdbcProjectionTest$1.process(JdbcProjectionTest.java:206)
	at akka.projection.jdbc.JdbcProjectionTest$1.process(JdbcProjectionTest.java:202)
	at akka.projection.jdbc.internal.JdbcHandlerAdapter.process(JdbcHandlerAdapter.scala:22)
	at akka.projection.jdbc.internal.JdbcProjectionImpl$$anon$2.$anonfun$process$4(JdbcProjectionImpl.scala:85)
	at akka.projection.jdbc.internal.JdbcProjectionImpl$$anon$2.$anonfun$process$4$adapted(JdbcProjectionImpl.scala:83)
	at akka.projection.jdbc.internal.JdbcSessionUtil$.$anonfun$withSession$1(JdbcSessionUtil.scala:33)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:671)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
<-- [akka.projection.jdbc.JdbcProjectionTest: atLeastOnceShouldRestartFromPreviousOffset] End of log messages of test that failed with expected:<abc|def|[ghi|]> but was:<abc|def|[]>
[info] - must save and retrieve MergeableOffset [H2 Database] (223 milliseconds)
[info] - atLeastOnceShouldRestartFromPreviousOffset *** FAILED ***
[info]   org.junit.ComparisonFailure: expected:<abc|def|[ghi|]> but was:<abc|def|[]>
[info]   at org.junit.Assert.assertEquals(Assert.java:117)
[info]   at org.junit.Assert.assertEquals(Assert.java:146)
[info]   at akka.projection.jdbc.JdbcProjectionTest.lambda$atLeastOnceShouldRestartFromPreviousOffset$2e5cadc3$1(JdbcProjectionTest.java:338)
[info]   at akka.projection.testkit.javadsl.ProjectionTestKit.$anonfun$runWithTestSink$1(ProjectionTestKit.scala:98)
[info]   at akka.projection.testkit.javadsl.ProjectionTestKit.$anonfun$runWithTestSink$1$adapted(ProjectionTestKit.scala:98)
[info]   at akka.projection.testkit.scaladsl.ProjectionTestKit.runWithTestSink(ProjectionTestKit.scala:126)
[info]   at akka.projection.testkit.javadsl.ProjectionTestKit.runWithTestSink(ProjectionTestKit.scala:98)
[info]   at akka.projection.jdbc.JdbcProjectionTest.atLeastOnceShouldRestartFromPreviousOffset(JdbcProjectionTest.java:327)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[info]   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
[info]   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[info]   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
[info]   at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[info]   at akka.actor.testkit.typed.javadsl.LogCapturing$$anon$1.evaluate(LogCapturing.scala:49)
```

**Comment by ennru** [comment]
https://travis-ci.com/github/akka/akka-projection/jobs/459384098#L676 in #485

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/3999762666/jobs/6864057802#step:6:418

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/4002445825/jobs/6869677583#step:6:359

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/4014243830/jobs/6894524261#step:6:347

**Comment by patriknw** [comment]
https://github.com/akka/akka-projection/actions/runs/6224125976/job/16891613094?pr=1010#step:6:462

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/6242597536/job/16946771743#step:6:462

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/6585799695/job/17892906200?pr=1049#step:6:462

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/7021658979/job/19104243608?pr=1073#step:6:544

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/7035198553/job/19145029717?pr=1073#step:6:442

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/7099127284/job/19322520902?pr=1082#step:6:439

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/7102501776/job/19333016214#step:6:438
