### ISSUE TITLE
failed: ProjectionBehaviorSpec - unexpected message StopObserved

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#544]
https://github.com/akka/akka-projection/pull/541/checks?check_run_id=2401876861

```
[info] - must work with ProjectionManagement extension *** FAILED *** (1 second, 555 milliseconds)
226
[info]   java.lang.AssertionError: Received unexpected message StopObserved
227
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
228
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectNoMessage_internal(TestProbeImpl.scala:213)
229
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectNoMessage(TestProbeImpl.scala:207)
230
[info]   at akka.projection.ProjectionBehaviorSpec.$anonfun$new$10(ProjectionBehaviorSpec.scala:462)
```

Flaky. Could have been introduced by the changes for pause/resume, but I can't see how?

The log capturing doesn't give anything. Looks like we are running tests in parallell? Captured logs include ErrorRateMetricExactlyOnceSpec

There is one comment in the test code that looks wrong, but I don't know if that matters:
https://github.com/akka/akka-projection/blob/badd73e7b28d6d28cacb320198bf2260600ed75f/akka-projection-core-test/src/test/scala/akka/projection/ProjectionBehaviorSpec.scala#L157-L161

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/3743525194/jobs/6355788687#step:6:199

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/3764777780/jobs/6399560990#step:6:228

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/3984221779/jobs/6830225014#step:6:213

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/3986398838/jobs/6834929471#step:6:296

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/4002064555/jobs/6868938834#step:6:203

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/4720375017/jobs/8372349122#step:6:394

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/4860192976/jobs/8663722279#step:6:287

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/6230862549/job/16911510690#step:6:401

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/6245017899/job/16952880034#step:6:359

**Comment by patriknw** [comment]
https://github.com/akka/akka-projection/actions/runs/6404406163/job/17384904399#step:6:342
