### ISSUE TITLE
failed: KafkaSourceProviderImplSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#641]
https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:445

```
[info] - must successfully verify offsets from assigned partitions *** FAILED *** (3 seconds, 677 milliseconds)
[446](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:446)
[info]   java.lang.AssertionError: timeout (3 seconds) while expecting 5 messages (got 4)
[447](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:447)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[448](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:448)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessages_internal$1(TestProbeImpl.scala:262)
[449](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:449)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessages_internal$1$adapted(TestProbeImpl.scala:257)
[450](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:450)
[info]   at scala.collection.immutable.Range.map(Range.scala:59)
[451](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:451)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessages_internal(TestProbeImpl.scala:257)
[452](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:452)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessages(TestProbeImpl.scala:244)
[453](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:453)
[info]   at akka.projection.kafka.internal.KafkaSourceProviderImplSpec.$anonfun$new$7(KafkaSourceProviderImplSpec.scala:113)
[454](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:454)
[info]   at akka.projection.kafka.internal.KafkaSourceProviderImplSpec.$anonfun$new$7$adapted(KafkaSourceProviderImplSpec.scala:88)
[455](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:455)
[info]   at akka.projection.testkit.scaladsl.ProjectionTestKit.runWithTestSink(ProjectionTestKit.scala:126)
[456](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:456)
[info]   at akka.projection.kafka.internal.KafkaSourceProviderImplSpec.$anonfun$new$2(KafkaSourceProviderImplSpec.scala:88)
[457](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:457)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[458](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:458)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[459](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:459)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[460](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:460)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[461](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:461)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[462](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:462)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[463](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:463)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
[464](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:464)
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:70)
[465](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:465)
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:68)
[466](https://github.com/akka/akka-projection/runs/5185067699?check_suite_focus=true#step:6:466)
[info]   at akka.projection.kafka.internal.KafkaSourceProviderImplSpec.withFixture(KafkaSourceProviderImplSpec.scala:46)
```

**Comment by octonato** [comment]
https://github.com/akka/akka-projection/runs/5160981274?check_suite_focus=true

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/3369675436/jobs/5589618921

Full logs
[logs_3205.zip](https://github.com/akka/akka-projection/files/9910222/logs_3205.zip)

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/3497151269/jobs/5855898749#step:6:448

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/3582275575/jobs/6026311185#step:6:439

**Comment by johanandren** [comment]
This is probably a hint, 5 of these, for topic-1 -> 5 to 10, not present when test passes:

> Source provider instructed projection to skip offset [MergeableOffset(Map(topic-1 -> 5))] with reason: The offset contains Kafka topic partitions that were revoked or lost in a previous rebalance

**Comment by johanandren** [comment]
I take that back, those warnings are expected and always there (but hidden by LogCapturing)

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/3748116544/jobs/6365087488#step:6:444

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/3713734857/jobs/6345068604#step:6:446

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/3764777780/jobs/6399561140#step:6:454

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/3713736112/jobs/6296748317#step:6:447
