### ISSUE TITLE
Incompatible Testcontainer Oracle image

### ISSUE THREAD

**Issue by octonato** [akka/akka-projection#644]
Not clear how we get to this. This used to work. 

Need to check if is consistently failing or sporadically.

https://github.com/akka/akka-projection/runs/5160989914?check_suite_focus=true#step:7:210
and in 
https://github.com/akka/akka-projection/runs/5160990184?check_suite_focus=true#step:7:169

```scala
[info] akka.projection.jdbc.OracleJdbcOffsetStoreSpec *** ABORTED *** (4 milliseconds)
[info]   java.lang.IllegalStateException: Failed to verify that image 'oracleinanutshell/oracle-xe-11g:1.0.0' is a compatible substitute for 'gvenzl/oracle-xe'. This generally means that you are trying to use an image that Testcontainers has not been designed to use. If this is deliberate, and if you are confident that the image is compatible, you should declare compatibility in code using the `asCompatibleSubstituteFor` method. For example:
[info]    DockerImageName myImage = DockerImageName.parse("oracleinanutshell/oracle-xe-11g:1.0.0").asCompatibleSubstituteFor("gvenzl/oracle-xe");
[info] and then use `myImage` instead.
[info]   at org.testcontainers.utility.DockerImageName.assertCompatibleWith(DockerImageName.java:248)
[info]   at org.testcontainers.containers.OracleContainer.<init>(OracleContainer.java:64)
[info]   at org.testcontainers.containers.OracleContainer.<init>(OracleContainer.java:59)
[info]   at akka.projection.jdbc.JdbcContainerOffsetStoreSpec$OracleSpecConfig$.newContainer(JdbcContainerOffsetStoreSpec.scala:108)
[info]   at akka.projection.jdbc.JdbcContainerOffsetStoreSpec$OracleSpecConfig$.newContainer(JdbcContainerOffsetStoreSpec.scala:101)
[info]   at akka.projection.jdbc.JdbcContainerOffsetStoreSpec$ContainerJdbcSpecConfig.initContainer(JdbcContainerOffsetStoreSpec.scala:57)
[info]   at akka.projection.jdbc.JdbcOffsetStoreSpec.$anonfun$beforeAll$1(JdbcOffsetStoreSpec.scala:131)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]   at scala.util.Try$.apply(Try.scala:210)
```

**Comment by octonato** [comment]
I will close this. I have run a few other builds today and didn't see it failing again.

**Comment by octonato** [comment]
Closed it too earlier. Just got another failure.

**Comment by octonato** [comment]
Oh gosh! The error is consistent and it happens each time on this PR: https://github.com/akka/akka-projection/pull/639 
And the PR is updating Testcontainers. Need to see if it's worth updating the image or ignoring #639 for now.
