### ISSUE TITLE
Failed: OffsetCommittedCounterMetricAtLeastOnceSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-projection#767]
https://github.com/akka/akka-projection/actions/runs/3764993334/jobs/6400006262#step:6:292

```
[info]   - must count offsets (with afterEnvelops optimization) *** FAILED *** (2 seconds, 997 milliseconds)
[info]     3 was not equal to 2 (OffsetCommittedCounterMetricSpec.scala:65)
[info]     org.scalatest.exceptions.TestFailedException:
[info]     at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)
[info]     at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:6778)
[info]     at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:6822)
[info]     at akka.projection.internal.metrics.OffsetCommittedCounterMetricAtLeastOnceSpec.$anonfun$new$7(OffsetCommittedCounterMetricSpec.scala:65)
[info]     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]     at akka.actor.testkit.typed.internal.TestProbeImpl.poll$1(TestProbeImpl.scala:374)
[info]     at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert_internal(TestProbeImpl.scala:391)
[info]     at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert(TestProbeImpl.scala:347))
[info]     at akka.projection.internal.metrics.tools.InternalProjectionStateMetricsSpec.runInternal(InternalProjectionStateMetricsSpec.scala:85)
[info]     at akka.projection.internal.metrics.OffsetCommittedCounterMetricAtLeastOnceSpec.$anonfun$new$6(OffsetCommittedCounterMetricSpec.scala:63)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/5374662684/jobs/9750284791#step:6:365

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/6242597536/job/16948238799#step:6:405
