### ISSUE TITLE
Flow based projection doesn't stop on stop message

### ISSUE THREAD

**Issue by johanandren** [akka/akka-projection#777]
Noted when working on the gRPC transport for RES: https://github.com/akka/akka-projection/pull/757#discussion_r1085237397

Configuring the sharded daemon process with the projection stop hangs the test and eventually reports of stuck actors.

**Comment by patriknw** [comment]
I can take a look at this

**Comment by patriknw** [comment]
@johanandren How did you observe that it didn't work? Which test is that?

I wrote a unit test with a flow based projection, and it stops the stream and ProjectionBehavior as expected. I aslo tried Peter's sample with the stop message included. It stops as expected when I add a second node to the Akka cluster. Sharding rebalance.

**Comment by johanandren** [comment]
Add stop message to the daemon process in ReplicationImpl and run ReplicationIntegrationSpec

**Comment by johanandren** [comment]
(Maybe it's just timing out and I misunderstood the error on shutdown/cleanup)

**Comment by patriknw** [comment]
I might see the problem now. When I disconnect from replica2 the grpc replication goes into a restart backoff and in that case it can't quickly rebalance
```
[1] of the entities in shard [3] not stopped after [5 seconds]. Maybe the handOffStopMessage [akka.projection.ProjectionBehavior$Stop$] is not handled? Waiting additional [55 seconds] before stopping the remaining entities.
```

**Comment by patriknw** [comment]
> run ReplicationIntegrationSpec

testContainers is not working for me (we are not friends)

**Comment by johanandren** [comment]
This is what I get at end of test if I add that stop message:

```
[info] akka.projection.grpc.replication.ReplicationIntegrationSpec *** ABORTED ***
[info]   java.lang.RuntimeException: Failed to stop [ReplicationIntegrationSpecB] within [10 seconds]
[info] -> / LocalActorRefProvider$$anon$2 class akka.actor.LocalActorRefProvider$Guardian status=0 2 children
[info]    ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 159 children
[info]    |   ⌊-> IO-TCP RepointableActorRef class akka.io.TcpManager status=0 1 children
[info]    |   |   ⌊-> selectors RoutedActorRef class akka.routing.RouterPoolActor status=0 1 children
[info]    |   |       ⌊-> $a LocalActorRef class akka.io.SelectionHandler status=0 1 children
[info]    |   |           ⌊-> 0 LocalActorRef class akka.io.TcpListener status=0 no children
[info]    |   ⌊-> Materializers RepointableActorRef class akka.stream.impl.MaterializerGuardian status=0 3 children
[info]    |   |   ⌊-> StreamSupervisor-3 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 no children
[info]    |   |   ⌊-> StreamSupervisor-4 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 6 children
[info]    |   |   |   ⌊-> remote-0-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   |   |   ⌊-> remote-2-0-unnamed RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   |   |   ⌊-> remote-3-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   |   |   ⌊-> remote-4-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   |   |   ⌊-> remote-5-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   |   |   ⌊-> remote-6-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   |   ⌊-> StreamSupervisor-5 LocalActorRef class akka.stream.impl.StreamSupervisor status=0 1 children
[info]    |   |       ⌊-> remoteControl-1-0-ignoreSink RepointableActorRef class akka.stream.impl.fusing.ActorGraphInterpreter status=0 no children
[info]    |   ⌊-> ShardedDaemonProcessKeepAlive-RES_hello-world_DCB_DCA RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> ShardedDaemonProcessKeepAlive-RES_hello-world_DCB_DCC RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> akka.persistence.r2dbc.journal RepointableActorRef class akka.persistence.r2dbc.journal.R2dbcJournal status=0 1 children
[info]    |   |   ⌊-> $a LocalActorRef class akka.persistence.journal.AsyncWriteJournal$Resequencer status=0 no children
[info]    |   ⌊-> akka.persistence.r2dbc.snapshot RepointableActorRef class akka.persistence.r2dbc.snapshot.R2dbcSnapshotStore status=0 no children
[info]    |   ⌊-> cluster RepointableActorRef class akka.cluster.ClusterDaemon status=0 2 children
[info]    |   |   ⌊-> core LocalActorRef class akka.cluster.ClusterCoreSupervisor status=0 2 children
[info]    |   |   |   ⌊-> daemon LocalActorRef class akka.cluster.ClusterCoreDaemon status=0 2 children
[info]    |   |   |   |   ⌊-> crossDcHeartbeatSender LocalActorRef class akka.cluster.CrossDcHeartbeatSender status=0 no children
[info]    |   |   |   |   ⌊-> heartbeatSender LocalActorRef class akka.cluster.ClusterHeartbeatSender status=0 no children
[info]    |   |   |   ⌊-> publisher LocalActorRef class akka.cluster.ClusterDomainEventPublisher status=0 no children
[info]    |   |   ⌊-> heartbeatReceiver LocalActorRef class akka.cluster.ClusterHeartbeatReceiver status=0 no children
[info]    |   ⌊-> clusterCommandManager RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> clusterEventBusListener RepointableActorRef class akka.cluster.ClusterReadView$$anon$1 status=0 no children
[info]    |   ⌊-> clusterReceptionist RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 1 children
[info]    |   |   ⌊-> replicator LocalActorRef class akka.cluster.ddata.Replicator status=0 no children
[info]    |   ⌊-> clusterStateSubscriptions RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> deadLetterListener RepointableActorRef class akka.event.DeadLetterListener status=0 no children
[info]    |   ⌊-> eventStreamUnsubscriber-2 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
[info]    |   ⌊-> eventstream RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> hello-worldShardCommandDelegator RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> log1-Slf4jLogger RepointableActorRef class akka.event.slf4j.Slf4jLogger status=0 no children
[info]    |   ⌊-> pool-master RepointableActorRef class akka.http.impl.engine.client.PoolMasterActor status=0 no children
[info]    |   ⌊-> projection-RES_hello-world_DCB_DCA RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> projection-RES_hello-world_DCB_DCC RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-0-7 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-1000-1007 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-1008-1015 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-1016-1023 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-104-111 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-112-119 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-120-127 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-128-135 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-136-143 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-144-151 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-152-159 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-16-23 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-160-167 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-168-175 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-176-183 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-184-191 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-192-199 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-200-207 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-208-215 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-216-223 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-224-231 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-232-239 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-24-31 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-240-247 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-248-255 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-256-263 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-264-271 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-272-279 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-280-287 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-288-295 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-296-303 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-304-311 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-312-319 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-32-39 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-320-327 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-328-335 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-336-343 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-344-351 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-352-359 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-360-367 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-368-375 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-376-383 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-384-391 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-392-399 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-40-47 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-400-407 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-408-415 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-416-423 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-424-431 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-432-439 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-440-447 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-448-455 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-456-463 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-464-471 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-472-479 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-48-55 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-480-487 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-488-495 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-496-503 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-504-511 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-512-519 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-520-527 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-528-535 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-536-543 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-544-551 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-552-559 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-56-63 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-560-567 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-568-575 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-576-583 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-584-591 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-592-599 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-600-607 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-608-615 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-616-623 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-624-631 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-632-639 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-64-71 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-640-647 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-648-655 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-656-663 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-664-671 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-672-679 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-680-687 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-688-695 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-696-703 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-704-711 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-712-719 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-72-79 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-720-727 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-728-735 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-736-743 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-744-751 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-752-759 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-760-767 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-768-775 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-776-783 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-784-791 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-792-799 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-8-15 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-80-87 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-800-807 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-808-815 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-816-823 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-824-831 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-832-839 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-840-847 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-848-855 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-856-863 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-864-871 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-872-879 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-88-95 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-880-887 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-888-895 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-896-903 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-904-911 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-912-919 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-920-927 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-928-935 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-936-943 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-944-951 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-952-959 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-96-103 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-960-967 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-968-975 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-976-983 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-984-991 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> r2dbc-hello-world-992-999 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> recoveryPermitter RepointableActorRef class akka.persistence.RecoveryPermitter status=0 no children
[info]    |   ⌊-> remote-deployment-watcher RepointableActorRef class akka.remote.RemoteDeploymentWatcher status=0 no children
[info]    |   ⌊-> remote-watcher RepointableActorRef class akka.cluster.ClusterRemoteWatcher status=0 no children
[info]    |   ⌊-> remoting-terminator RepointableActorRef class akka.remote.RemoteActorRefProvider$RemotingTerminator status=0 no children
[info]    |   ⌊-> sharded-daemon-process-RES_hello-world_DCB_DCAShardCommandDelegator RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> sharded-daemon-process-RES_hello-world_DCB_DCCShardCommandDelegator RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> sharding RepointableActorRef class akka.cluster.sharding.ClusterShardingGuardian status=0 5 children
[info]    |   |   ⌊-> hello-worldCoordinator LocalActorRef class akka.cluster.singleton.ClusterSingletonManager status=0 2 children
[info]    |   |   |   ⌊-> $a LocalActorRef class akka.cluster.singleton.ClusterSingletonManager$Internal$OldestChangedBuffer status=0 no children
[info]    |   |   |   ⌊-> singleton LocalActorRef class akka.pattern.internal.BackoffOnStopSupervisor status=0 1 children
[info]    |   |   |       ⌊-> coordinator LocalActorRef class akka.cluster.sharding.DDataShardCoordinator status=0 no children
[info]    |   |   ⌊-> replicator LocalActorRef class akka.cluster.ddata.Replicator status=0 no children
[info]    |   |   ⌊-> sharded-daemon-process-RES_hello-world_DCB_DCA LocalActorRef class akka.cluster.sharding.ShardRegion status=0 no children
[info]    |   |   ⌊-> sharded-daemon-process-RES_hello-world_DCB_DCACoordinator LocalActorRef class akka.cluster.singleton.ClusterSingletonManager status=0 2 children
[info]    |   |   |   ⌊-> $a LocalActorRef class akka.cluster.singleton.ClusterSingletonManager$Internal$OldestChangedBuffer status=0 no children
[info]    |   |   |   ⌊-> singleton LocalActorRef class akka.pattern.internal.BackoffOnStopSupervisor status=0 1 children
[info]    |   |   |       ⌊-> coordinator LocalActorRef class akka.cluster.sharding.DDataShardCoordinator status=0 no children
[info]    |   |   ⌊-> sharded-daemon-process-RES_hello-world_DCB_DCCCoordinator LocalActorRef class akka.cluster.singleton.ClusterSingletonManager status=0 2 children
[info]    |   |       ⌊-> $a LocalActorRef class akka.cluster.singleton.ClusterSingletonManager$Internal$OldestChangedBuffer status=0 no children
[info]    |   |       ⌊-> singleton LocalActorRef class akka.pattern.internal.BackoffOnStopSupervisor status=0 1 children
[info]    |   |           ⌊-> coordinator LocalActorRef class akka.cluster.sharding.DDataShardCoordinator status=0 no children
[info]    |   ⌊-> test-2 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> testProbe-11 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> testProbe-2 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> testProbe-5 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    |   ⌊-> testProbe-8 RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
[info]    ⌊-> user LocalActorRef class akka.actor.LocalActorRefProvider$Guardian status=0 no children
[info]   at akka.actor.testkit.typed.internal.TestKitUtils$.shutdown(TestKitUtils.scala:89)
[info]   at akka.actor.testkit.typed.scaladsl.ActorTestKit$.shutdown(ActorTestKit.scala:154)
[info]   at akka.projection.grpc.replication.ReplicationIntegrationSpec.$anonfun$afterAll$1(ReplicationIntegrationSpec.scala:319)
[info]   at akka.projection.grpc.replication.ReplicationIntegrationSpec.$anonfun$afterAll$1$adapted(ReplicationIntegrationSpec.scala:318)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at akka.projection.grpc.replication.ReplicationIntegrationSpec.afterAll(ReplicationIntegrationSpec.scala:318)
[info]   at org.scalatest.BeforeAndAfterAll.$anonfun$run$1(BeforeAndAfterAll.scala:225)
[info]   at org.scalatest.Status.$anonfun$withAfterEffect$1(Status.scala:377)
[info]   at org.scalatest.Status.$anonfun$withAfterEffect$1$adapted(Status.scala:373)
[info]   at org.scalatest.CompositeStatus.whenCompleted(Status.scala:962)
[info]   ...
```

**Comment by patriknw** [comment]
I see
```
[info] [2023-01-25 16:03:52,371] [WARN] [akka.stream.scaladsl.RestartWithBackoffSource] [akka://ShoppingCartService@127.0.0.1:7101] [] [ShoppingCartService-akka.actor.default-dispatcher-30] - Restarting stream due to failure [11]: java.lang.RuntimeException: Failure to consume gRPC event stream for [replicated-shopping-cart]
[info] java.lang.RuntimeException: Failure to consume gRPC event stream for [replicated-shopping-cart]
[info] 	at akka.projection.grpc.consumer.scaladsl.GrpcReadJournal$$anonfun$1.applyOrElse(GrpcReadJournal.scala:264)
[info] 	at akka.projection.grpc.consumer.scaladsl.GrpcReadJournal$$anonfun$1.applyOrElse(GrpcReadJournal.scala:262)
```

I think that while the RestartSource is in backoff it can't be interrupted by the killswitch from the projection.

One thing that drives me crazy is that I can't find where this RestartSource is created.

**Comment by johanandren** [comment]
`RunningProjection.withBackoff` ?

**Comment by patriknw** [comment]
Thanks, that's it.

**Comment by patriknw** [comment]
For the record, the testcontainer problem was this (again): https://github.com/testcontainers/testcontainers-java/issues/5034#issuecomment-1036155978

```
export TESTCONTAINERS_RYUK_DISABLED=true
```
