### ISSUE TITLE
failed: JdbcProjectionSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-projection#784]
https://github.com/akka/akka-projection/actions/runs/4015991342/jobs/6898414054#step:7:2177

```
[info] - must store offset for failing events when using RecoveryStrategy.skip *** FAILED *** (308 milliseconds)
[info]   Some(5) was not equal to Some(6) (JdbcProjectionSpec.scala:232)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6982)
[info]   at akka.projection.jdbc.JdbcProjectionSpec.offsetShouldBe(JdbcProjectionSpec.scala:232)
[info]   at akka.projection.jdbc.JdbcProjectionSpec.$anonfun$new$9(JdbcProjectionSpec.scala:362)
```

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/4293237834/jobs/7480664623#step:7:7185

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/4293237834/jobs/7492926441#step:7:15741

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/5069905279/jobs/9104170419?pr=904#step:7:136

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/5374675168/jobs/9750309670#step:7:292

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/6426014038/job/17449570199#step:7:14727
