### ISSUE TITLE
failed: ReplicationIntegrationSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#834]
```
[info] - should replicate concurrent writes to the other DCs *** FAILED *** (20 seconds, 175 milliseconds)
[11855](https://github.com/akka/akka-projection/actions/runs/4543677497/jobs/8008672913#step:6:11856)
[info]   Greeting 2 for entity id one Set("hello 2 from DCA", "hello 2 from DCC") had size 2 instead of expected size 1 (ReplicationIntegrationSpec.scala:303)

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/4830399356/jobs/8606583184?pr=876#step:6:9248

**Comment by patriknw** [comment]
https://github.com/akka/akka-projection/actions/runs/4869921841/jobs/8685022703?pr=876#step:6:9139

```
[info] - should replicate concurrent writes to the other DCs *** FAILED *** (20 seconds, 52 milliseconds)
[info]   Greeting 2 for entity id one Set("hello 2 from DCA", "hello 2 from DCC") had size 2 instead of expected size 1 (ReplicationIntegrationSpec.scala:303)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[info]   at org.scalatest.matchers.should.Matchers$ResultOfHaveWordForExtent.size(Matchers.scala:2805)
[info]   at akka.projection.grpc.replication.ReplicationIntegrationSpec.$anonfun$new$29(ReplicationIntegrationSpec.scala:303)
[info]   at org.scalatest.Assertions.withClue(Assertions.scala:1065)
[info]   at org.scalatest.Assertions.withClue$(Assertions.scala:1052)
[info]   at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.withClue(ScalaTestWithActorTestKit.scala:31)
[info]   at akka.projection.grpc.replication.ReplicationIntegrationSpec.$anonfun$new$28(ReplicationIntegrationSpec.scala:303)
[info]   at scala.collection.immutable.Set$Set3.foreach(Set.scala:252)
[info]   at akka.projection.grpc.replication.ReplicationIntegrationSpec.$anonfun$new$27(ReplicationIntegrationSpec.scala:294)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.poll$1(TestProbeImpl.scala:374)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert_internal(TestProbeImpl.scala:391)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.awaitAssert(TestProbeImpl.scala:350)
[info]   at akka.projection.grpc.replication.ReplicationIntegrationSpec.$anonfun$new$22(ReplicationIntegrationSpec.scala:307)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]   at org.scalatest.Assertions.withClue(Assertions.scala:1065)
[info]   at org.scalatest.Assertions.withClue$(Assertions.scala:1052)
[info]   at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.withClue(ScalaTestWithActorTestKit.scala:31)
[info]   at akka.projection.grpc.replication.ReplicationIntegrationSpec.$anonfun$new$21(ReplicationIntegrationSpec.scala:274)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
[info]   at akka.projection.grpc.replication.ReplicationIntegrationSpec.$anonfun$new$20(ReplicationIntegrationSpec.scala:273)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/5265497688/jobs/9518201345?pr=914

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/5476704340/jobs/9974631768?pr=932#step:6:6178

**Comment by pvlugter** [comment]
https://github.com/akka/akka-projection/actions/runs/5706158919/job/15461593463?pr=946#step:6:9338
