### ISSUE TITLE
Failed: HandlerRecoveryImplSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-projection#859]
https://github.com/akka/akka-projection/actions/runs/4729347937/jobs/8391770455#step:6:307

```
--> [akka.projection.internal.HandlerRecoveryImplSpec: HandlerRecovery must abort retryAndFail when retrying] Start of log messages of test that [Failed(java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for Err(Envelope(3,c),akka.actor.testkit.typed.TestException: err))]
[2023-04-18 06:40:45,177] [INFO] [akka.actor.testkit.typed.scaladsl.LogCapturing] [] [pool-6-thread-94-ScalaTest-running-HandlerRecoveryImplSpec] - Logging finished for test [akka.projection.internal.HandlerRecoveryImplSpec: HandlerRecovery must abort retryAndFail when retrying] that [Failed(java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for Err(Envelope(3,c),akka.actor.testkit.typed.TestException: err))] MDC: {}
<-- [akka.projection.internal.HandlerRecoveryImplSpec: HandlerRecovery must abort retryAndFail when retrying] End of log messages of test that [Failed(java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for Err(Envelope(3,c),akka.actor.testkit.typed.TestException: err))]
[info] - must abort retryAndFail when retrying *** FAILED *** (4 seconds, 110 milliseconds)
[info]   java.lang.AssertionError: timeout (3 seconds) during expectMessage while waiting for Err(Envelope(3,c),akka.actor.testkit.typed.TestException: err)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage_internal(TestProbeImpl.scala:171)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessage(TestProbeImpl.scala:149)
[info]   at akka.projection.internal.HandlerRecoveryImplSpec.$anonfun$new$21(HandlerRecoveryImplSpec.scala:242)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1240)
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:70)
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:68)
[info]   at akka.projection.internal.HandlerRecoveryImplSpec.withFixture(HandlerRecoveryImplSpec.scala:44)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-projection/actions/runs/5401120618/jobs/9810490918?pr=932#step:6:401
