### ISSUE TITLE
testcontainers.containers Mounts denied

### ISSUE THREAD

**Issue by patriknw** [akka/akka-projection#90]
Do I need configure anything in Docker Desktop to be able to use the test containers locally?

```
[info]   Cause: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageNameFuture=java.util.concurrent.CompletableFuture@3e825116[Completed normally], imagePullPolicy=DefaultPullPolicy(), dockerClient=LazyDockerClient.INSTANCE)
[info]   at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1265)
[info]   at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:600)
[info]   at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:311)
[info]   at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302)
[info]   at com.dimafeng.testcontainers.SingleContainer.start(Container.scala:46)
[info]   at akka.projection.cassandra.ContainerSessionProvider$.$anonfun$started$1(ContainerSessionProvider.scala:44)
...
[info]   Cause: com.github.dockerjava.api.exception.InternalServerErrorException: Mounts denied: EOF
[info]   at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:287)
[info]   at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:265)
[info]   at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:126)
[info]   at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:28)

```

**Comment by bsideup** [comment]
I wonder if you're hitting the same issue as in https://github.com/testcontainers/testcontainers-java/issues/730#issuecomment-394347524

Could you please check your mounts?

**Comment by patriknw** [comment]
I have /private and /tmp

<img width="477" alt="Screenshot 2020-05-06 at 17 37 43" src="https://user-images.githubusercontent.com/336161/81197264-5d4c5d80-8fc0-11ea-84f0-aa3521c649fd.png">

This is not an urgent issue for me, I will anyway run it without docker. Wanted to log the issue since contributors will probably hit same thing.

**Comment by seglo** [comment]
I'm curious, do you run `docker` commands as root or your user?  I can do some troubleshooting on a mac later.

**Comment by patriknw** [comment]
> do you run docker commands as root or your user?

I just ran `sbt test` and expected that it would start the test container automatically. Do you mean that it requires `sudo sbt` or do I need to run some other docker command on the side?

**Comment by seglo** [comment]
No, I mean when you issue regular `docker` commands can you execute them with your user account or do you run as root?

**Comment by patriknw** [comment]
ok, that works as user
